### ISSUE TITLE
Buttons missed

### ISSUE THREAD

**Issue by vgjm** [NaturalSelectionLabs/Web3Pass#156]
**Describe the bug**
Buttons are missed on the edit profile page

**To Reproduce**
Simply open this link [Edit Profile](https://yohoo.eth.rss3.bio/profile)
If I set the scalability to 100%. Then I can't see the 'Discard' and 'Save' buttons. Even if I scroll down to the bottom.

**Expected behavior**
See the 'Save' and 'Discard' buttons when I scroll down.

**Screenshots**
[EditProfile](https://bafybeibcfvnmh3bbbdozjxs6eqdpjsgdefnhl5jozn6rrkhdoxkrfbuuzq.ipfs.dweb.link/)

**Desktop (please complete the following information):**
 - Windows
 - Edge, Chrome, Firefox and Brave
 - Windows11 22523.1000

**Comment by Candinya** [comment]
Thanks for your help. Fixed in 4229f60a13cb4758c3301c9bf2abef8973c6b396 .
