### ISSUE TITLE
Unable to load mirror contents

### ISSUE THREAD

**Issue by suclogger** [NaturalSelectionLabs/Web3Pass#157]
**Describe the bug**
On rss3 main page, there's problem loading mirror contents.

**To Reproduce**
1. Go to any rss3 main page such as 'https://runbao.eth.rss3.bio/'
2. Content area stay empty while having corresponding mirror contents.

**Expected behavior**
Content area display mirror contents.
**Screenshots**
<img width="1022" alt="runbao 2021-12-22 01-47-38" src="https://user-images.githubusercontent.com/8472155/146975443-05c10baa-b222-4d3a-bcf0-8d1762ca5763.png">

**Additional context**
chrome console error log as follow:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'date_created')
    at Object.initContent (index.ff5f166c.js?f3ee37bf46d24130f7df:2)
    at async index.ff5f166c.js?f3ee37bf46d24130f7df:2

**Comment by Candinya** [comment]
Thanks for your help. Fixed in 8c6f0a670c9284334bd71a04e01021c429d56fd2 .

**Comment by suclogger** [comment]
Confirm solved. Really quick response 👍.
